language: php

php:
    - 5.3

before_install:
    - cd install
    - sudo ./zmq22-install.sh
    - sudo ./zmqphp-install.sh
    - ./zmq-version.sh
    - sudo ./mongrel2-zmq2-install.sh
    - sudo ./pecl-http-install.sh

script: phpunit -c test/phpunit.xml .
