language: php

php:
    - 5.3

before_install:
    - echo '[Installing Prerequisites]'
    - ./install/ci-bootstrap.sh > /dev/null 2>&1

script: phpunit --bootstrap=examples/autoloader.php -c test/phpunit.xml .

